export interface MasterDataItem {
  sNo: number;
  category: string;
  lineItem: string;
  unit: string;
  rate: number;
  sku: string;
}

export const customMasterData: MasterDataItem[] = [
  { sNo: 1, category: "Portable Cabins / Site Cabins", lineItem: "Cabin structure — base unit", unit: "sq.ft", rate: 850, sku: "CAB-001" },
  { sNo: 2, category: "Portable Cabins / Site Cabins", lineItem: "Fans", unit: "nos", rate: 1200, sku: "CAB-002" },
  { sNo: 3, category: "Portable Cabins / Site Cabins", lineItem: "Air Conditioner", unit: "nos", rate: 28000, sku: "CAB-003" },
  { sNo: 4, category: "Portable Cabins / Site Cabins", lineItem: "Windows", unit: "nos", rate: 3500, sku: "CAB-004" },
  { sNo: 5, category: "Portable Cabins / Site Cabins", lineItem: "Doors", unit: "nos", rate: 4500, sku: "CAB-005" },
  { sNo: 6, category: "Portable Cabins / Site Cabins", lineItem: "Lights / LED fittings", unit: "nos", rate: 350, sku: "CAB-006" },
  { sNo: 7, category: "Portable Cabins / Site Cabins", lineItem: "Commode / WC", unit: "nos", rate: 3800, sku: "CAB-007" },
  { sNo: 8, category: "Portable Cabins / Site Cabins", lineItem: "Wash basin", unit: "nos", rate: 2200, sku: "CAB-008" },
  { sNo: 9, category: "Portable Cabins / Site Cabins", lineItem: "Flooring — vinyl/PVC", unit: "sq.ft", rate: 65, sku: "CAB-009" },
  { sNo: 10, category: "Portable Cabins / Site Cabins", lineItem: "Insulation — PUF panel", unit: "sq.ft", rate: 180, sku: "CAB-010" },
  { sNo: 11, category: "Portable Cabins / Site Cabins", lineItem: "Electrical wiring & switchboard", unit: "lump sum", rate: 15000, sku: "CAB-011" },
  { sNo: 12, category: "Portable Cabins / Site Cabins", lineItem: "Water tank & plumbing", unit: "lump sum", rate: 12000, sku: "CAB-012" },
  { sNo: 13, category: "Portable Cabins / Site Cabins", lineItem: "Exhaust fan", unit: "nos", rate: 1800, sku: "CAB-013" },
  { sNo: 14, category: "Portable Cabins / Site Cabins", lineItem: "Cabin painting/exterior finish", unit: "sq.ft", rate: 40, sku: "CAB-014" },
  { sNo: 15, category: "Portable Cabins / Site Cabins", lineItem: "Transportation & installation", unit: "lump sum", rate: 25000, sku: "CAB-015" },
  { sNo: 16, category: "Modular Kitchen", lineItem: "Base cabinets", unit: "running ft", rate: 1400, sku: "KIT-016" },
  { sNo: 17, category: "Modular Kitchen", lineItem: "Wall cabinets", unit: "running ft", rate: 1100, sku: "KIT-017" },
  { sNo: 18, category: "Modular Kitchen", lineItem: "Countertop — granite/quartz", unit: "sq.ft", rate: 220, sku: "KIT-018" },
  { sNo: 19, category: "Modular Kitchen", lineItem: "Chimney", unit: "nos", rate: 12000, sku: "KIT-019" },
  { sNo: 20, category: "Modular Kitchen", lineItem: "Hob / cooktop", unit: "nos", rate: 8000, sku: "KIT-020" },
  { sNo: 21, category: "Modular Kitchen", lineItem: "Sink & faucet", unit: "nos", rate: 4500, sku: "KIT-021" },
  { sNo: 22, category: "Modular Kitchen", lineItem: "Tall unit / pantry unit", unit: "nos", rate: 18000, sku: "KIT-022" },
  { sNo: 23, category: "Modular Kitchen", lineItem: "Drawer channels & baskets", unit: "nos", rate: 2200, sku: "KIT-023" },
  { sNo: 24, category: "Modular Kitchen", lineItem: "Handles & hardware", unit: "set", rate: 1500, sku: "KIT-024" },
  { sNo: 25, category: "Modular Kitchen", lineItem: "Backsplash tiling", unit: "sq.ft", rate: 90, sku: "KIT-025" },
  { sNo: 26, category: "Modular Kitchen", lineItem: "Under-cabinet lighting", unit: "running ft", rate: 350, sku: "KIT-026" },
  { sNo: 27, category: "Modular Kitchen", lineItem: "Appliance provision (oven/microwave)", unit: "nos", rate: 6000, sku: "KIT-027" },
  { sNo: 28, category: "Office Interior Fit-out", lineItem: "Workstations", unit: "nos", rate: 15000, sku: "OFF-028" },
  { sNo: 29, category: "Office Interior Fit-out", lineItem: "Cabin partitions — glass/gypsum", unit: "sq.ft", rate: 320, sku: "OFF-029" },
  { sNo: 30, category: "Office Interior Fit-out", lineItem: "False ceiling", unit: "sq.ft", rate: 85, sku: "OFF-030" },
  { sNo: 31, category: "Office Interior Fit-out", lineItem: "Flooring — carpet/vinyl", unit: "sq.ft", rate: 75, sku: "OFF-031" },
  { sNo: 32, category: "Office Interior Fit-out", lineItem: "Conference table & chairs", unit: "set", rate: 45000, sku: "OFF-032" },
  { sNo: 33, category: "Office Interior Fit-out", lineItem: "Reception desk", unit: "nos", rate: 35000, sku: "OFF-033" },
  { sNo: 34, category: "Office Interior Fit-out", lineItem: "Electrical & data points", unit: "nos", rate: 900, sku: "OFF-034" },
  { sNo: 35, category: "Office Interior Fit-out", lineItem: "HVAC ducting", unit: "lump sum", rate: 80000, sku: "OFF-035" },
  { sNo: 36, category: "Office Interior Fit-out", lineItem: "Painting", unit: "sq.ft", rate: 25, sku: "OFF-036" },
  { sNo: 37, category: "Office Interior Fit-out", lineItem: "Signage & branding wall", unit: "lump sum", rate: 20000, sku: "OFF-037" },
  { sNo: 38, category: "Office Interior Fit-out", lineItem: "Pantry setup", unit: "lump sum", rate: 60000, sku: "OFF-038" },
  { sNo: 39, category: "Residential Interior Fit-out", lineItem: "Wardrobes", unit: "running ft", rate: 1800, sku: "RES-039" },
  { sNo: 40, category: "Residential Interior Fit-out", lineItem: "False ceiling with cove lighting", unit: "sq.ft", rate: 95, sku: "RES-040" },
  { sNo: 41, category: "Residential Interior Fit-out", lineItem: "TV unit / entertainment unit", unit: "nos", rate: 25000, sku: "RES-041" },
  { sNo: 42, category: "Residential Interior Fit-out", lineItem: "Modular kitchen (complete)", unit: "lump sum", rate: 18000, sku: "RES-042" },
  { sNo: 43, category: "Residential Interior Fit-out", lineItem: "Bedroom wardrobes", unit: "running ft", rate: 1800, sku: "RES-043" },
  { sNo: 44, category: "Residential Interior Fit-out", lineItem: "Wall panelling", unit: "sq.ft", rate: 150, sku: "RES-044" },
  { sNo: 45, category: "Residential Interior Fit-out", lineItem: "Flooring — tiles/wood", unit: "sq.ft", rate: 85, sku: "RES-045" },
  { sNo: 46, category: "Residential Interior Fit-out", lineItem: "Painting — interior", unit: "sq.ft", rate: 22, sku: "RES-046" },
  { sNo: 47, category: "Residential Interior Fit-out", lineItem: "Curtains & blinds", unit: "running ft", rate: 450, sku: "RES-047" },
  { sNo: 48, category: "Residential Interior Fit-out", lineItem: "Electrical rewiring", unit: "lump sum", rate: 45000, sku: "RES-048" },
  { sNo: 49, category: "HVAC Systems", lineItem: "Split AC unit", unit: "nos", rate: 32000, sku: "HVC-049" },
  { sNo: 50, category: "HVAC Systems", lineItem: "VRV/VRF outdoor unit", unit: "nos", rate: 250000, sku: "HVC-050" },
  { sNo: 51, category: "HVAC Systems", lineItem: "Ductable AC unit", unit: "nos", rate: 85000, sku: "HVC-051" },
  { sNo: 52, category: "HVAC Systems", lineItem: "Ducting — insulated", unit: "running ft", rate: 550, sku: "HVC-052" },
  { sNo: 53, category: "HVAC Systems", lineItem: "Diffusers & grilles", unit: "nos", rate: 850, sku: "HVC-053" },
  { sNo: 54, category: "HVAC Systems", lineItem: "Thermostat/controller", unit: "nos", rate: 3500, sku: "HVC-054" },
  { sNo: 55, category: "HVAC Systems", lineItem: "Copper piping", unit: "running ft", rate: 320, sku: "HVC-055" },
  { sNo: 56, category: "HVAC Systems", lineItem: "Exhaust/ventilation fan", unit: "nos", rate: 2200, sku: "HVC-056" },
  { sNo: 57, category: "HVAC Systems", lineItem: "Chiller unit", unit: "nos", rate: 450000, sku: "HVC-057" },
  { sNo: 58, category: "HVAC Systems", lineItem: "Cooling tower", unit: "nos", rate: 180000, sku: "HVC-058" },
  { sNo: 59, category: "Electrical Installation", lineItem: "Main distribution board (MDB)", unit: "nos", rate: 25000, sku: "ELE-059" },
  { sNo: 60, category: "Electrical Installation", lineItem: "MCB/DB boards", unit: "nos", rate: 3500, sku: "ELE-060" },
  { sNo: 61, category: "Electrical Installation", lineItem: "Wiring — concealed", unit: "running ft", rate: 45, sku: "ELE-061" },
  { sNo: 62, category: "Electrical Installation", lineItem: "Switches & sockets", unit: "nos", rate: 250, sku: "ELE-062" },
  { sNo: 63, category: "Electrical Installation", lineItem: "LED lights — panel/downlight", unit: "nos", rate: 450, sku: "ELE-063" },
  { sNo: 64, category: "Electrical Installation", lineItem: "Ceiling fan", unit: "nos", rate: 1600, sku: "ELE-064" },
  { sNo: 65, category: "Electrical Installation", lineItem: "Earthing system", unit: "lump sum", rate: 8000, sku: "ELE-065" },
  { sNo: 66, category: "Electrical Installation", lineItem: "Cable trays", unit: "running ft", rate: 220, sku: "ELE-066" },
  { sNo: 67, category: "Electrical Installation", lineItem: "DG set / generator", unit: "nos", rate: 350000, sku: "ELE-067" },
  { sNo: 68, category: "Electrical Installation", lineItem: "UPS / inverter backup", unit: "nos", rate: 22000, sku: "ELE-068" },
  { sNo: 69, category: "Plumbing & Sanitary", lineItem: "CPVC/PVC piping", unit: "running ft", rate: 55, sku: "PLU-069" },
  { sNo: 70, category: "Plumbing & Sanitary", lineItem: "Wash basin", unit: "nos", rate: 2500, sku: "PLU-070" },
  { sNo: 71, category: "Plumbing & Sanitary", lineItem: "Commode — western/Indian", unit: "nos", rate: 6500, sku: "PLU-071" },
  { sNo: 72, category: "Plumbing & Sanitary", lineItem: "Shower & fittings", unit: "set", rate: 4500, sku: "PLU-072" },
  { sNo: 73, category: "Plumbing & Sanitary", lineItem: "Kitchen sink", unit: "nos", rate: 3500, sku: "PLU-073" },
  { sNo: 74, category: "Plumbing & Sanitary", lineItem: "Water tank — overhead/underground", unit: "nos", rate: 18000, sku: "PLU-074" },
  { sNo: 75, category: "Plumbing & Sanitary", lineItem: "Motor & pump", unit: "nos", rate: 9500, sku: "PLU-075" },
  { sNo: 76, category: "Plumbing & Sanitary", lineItem: "Drainage piping", unit: "running ft", rate: 65, sku: "PLU-076" },
  { sNo: 77, category: "Plumbing & Sanitary", lineItem: "Bib cocks & valves", unit: "nos", rate: 350, sku: "PLU-077" },
  { sNo: 78, category: "Plumbing & Sanitary", lineItem: "Geyser / water heater", unit: "nos", rate: 7500, sku: "PLU-078" },
  { sNo: 79, category: "Solar Power Systems", lineItem: "Solar panels", unit: "nos", rate: 12000, sku: "SOL-079" },
  { sNo: 80, category: "Solar Power Systems", lineItem: "Inverter — on-grid/off-grid", unit: "nos", rate: 45000, sku: "SOL-080" },
  { sNo: 81, category: "Solar Power Systems", lineItem: "Mounting structure", unit: "lump sum", rate: 15000, sku: "SOL-081" },
  { sNo: 82, category: "Solar Power Systems", lineItem: "Battery bank", unit: "nos", rate: 22000, sku: "SOL-082" },
  { sNo: 83, category: "Solar Power Systems", lineItem: "DC/AC cabling", unit: "running ft", rate: 120, sku: "SOL-083" },
  { sNo: 84, category: "Solar Power Systems", lineItem: "Net metering setup", unit: "lump sum", rate: 8000, sku: "SOL-084" },
  { sNo: 85, category: "Solar Power Systems", lineItem: "Earthing & lightning arrestor", unit: "lump sum", rate: 6000, sku: "SOL-085" },
  { sNo: 86, category: "Solar Power Systems", lineItem: "Installation & commissioning", unit: "lump sum", rate: 20000, sku: "SOL-086" },
  { sNo: 87, category: "CCTV & Security Systems", lineItem: "Dome camera", unit: "nos", rate: 2800, sku: "SEC-087" },
  { sNo: 88, category: "CCTV & Security Systems", lineItem: "Bullet camera", unit: "nos", rate: 3200, sku: "SEC-088" },
  { sNo: 89, category: "CCTV & Security Systems", lineItem: "PTZ camera", unit: "nos", rate: 18000, sku: "SEC-089" },
  { sNo: 90, category: "CCTV & Security Systems", lineItem: "DVR/NVR unit", unit: "nos", rate: 8500, sku: "SEC-090" },
  { sNo: 91, category: "CCTV & Security Systems", lineItem: "Hard disk storage", unit: "nos", rate: 4500, sku: "SEC-091" },
  { sNo: 92, category: "CCTV & Security Systems", lineItem: "Cabling — coaxial/CAT6", unit: "running ft", rate: 25, sku: "SEC-092" },
  { sNo: 93, category: "CCTV & Security Systems", lineItem: "Video door phone", unit: "nos", rate: 6500, sku: "SEC-093" },
  { sNo: 94, category: "CCTV & Security Systems", lineItem: "Access control — biometric/RFID", unit: "nos", rate: 9500, sku: "SEC-094" },
  { sNo: 95, category: "CCTV & Security Systems", lineItem: "Monitor/display", unit: "nos", rate: 7500, sku: "SEC-095" },
  { sNo: 96, category: "CCTV & Security Systems", lineItem: "Installation & configuration", unit: "lump sum", rate: 10000, sku: "SEC-096" },
  { sNo: 97, category: "Fire Safety Systems", lineItem: "Fire extinguishers", unit: "nos", rate: 1800, sku: "FIR-097" },
  { sNo: 98, category: "Fire Safety Systems", lineItem: "Smoke detectors", unit: "nos", rate: 1200, sku: "FIR-098" },
  { sNo: 99, category: "Fire Safety Systems", lineItem: "Fire alarm panel", unit: "nos", rate: 35000, sku: "FIR-099" },
  { sNo: 100, category: "Fire Safety Systems", lineItem: "Sprinkler system", unit: "points", rate: 950, sku: "FIR-100" },
  { sNo: 101, category: "Fire Safety Systems", lineItem: "Hydrant system", unit: "lump sum", rate: 120000, sku: "FIR-101" },
  { sNo: 102, category: "Fire Safety Systems", lineItem: "Fire hose reel", unit: "nos", rate: 6500, sku: "FIR-102" },
  { sNo: 103, category: "Fire Safety Systems", lineItem: "Emergency exit signage", unit: "nos", rate: 450, sku: "FIR-103" },
  { sNo: 104, category: "Fire Safety Systems", lineItem: "Fire rated doors", unit: "nos", rate: 18000, sku: "FIR-104" },
  { sNo: 105, category: "Fire Safety Systems", lineItem: "Hooter/siren", unit: "nos", rate: 1500, sku: "FIR-105" },
  { sNo: 106, category: "False Ceiling & POP", lineItem: "Gypsum board ceiling", unit: "sq.ft", rate: 75, sku: "CLG-106" },
  { sNo: 107, category: "False Ceiling & POP", lineItem: "POP cornice work", unit: "running ft", rate: 90, sku: "CLG-107" },
  { sNo: 108, category: "False Ceiling & POP", lineItem: "Grid/mineral fiber ceiling", unit: "sq.ft", rate: 65, sku: "CLG-108" },
  { sNo: 109, category: "False Ceiling & POP", lineItem: "Cove lighting channel", unit: "running ft", rate: 180, sku: "CLG-109" },
  { sNo: 110, category: "False Ceiling & POP", lineItem: "Bulkhead/step design", unit: "running ft", rate: 120, sku: "CLG-110" },
  { sNo: 111, category: "False Ceiling & POP", lineItem: "Access panels", unit: "nos", rate: 850, sku: "CLG-111" },
  { sNo: 112, category: "False Ceiling & POP", lineItem: "Painting/finishing", unit: "sq.ft", rate: 20, sku: "CLG-112" },
  { sNo: 113, category: "Flooring", lineItem: "Vitrified tiles", unit: "sq.ft", rate: 65, sku: "FLR-113" },
  { sNo: 114, category: "Flooring", lineItem: "Marble/granite", unit: "sq.ft", rate: 180, sku: "FLR-114" },
  { sNo: 115, category: "Flooring", lineItem: "Wooden/laminate flooring", unit: "sq.ft", rate: 120, sku: "FLR-115" },
  { sNo: 116, category: "Flooring", lineItem: "Epoxy flooring", unit: "sq.ft", rate: 90, sku: "FLR-116" },
  { sNo: 117, category: "Flooring", lineItem: "Skirting", unit: "running ft", rate: 35, sku: "FLR-117" },
  { sNo: 118, category: "Flooring", lineItem: "Anti-skid tiles — wet areas", unit: "sq.ft", rate: 55, sku: "FLR-118" },
  { sNo: 119, category: "Flooring", lineItem: "Floor levelling/screeding", unit: "sq.ft", rate: 25, sku: "FLR-119" },
  { sNo: 120, category: "Painting & Waterproofing", lineItem: "Interior wall painting", unit: "sq.ft", rate: 18, sku: "PNT-120" },
  { sNo: 121, category: "Painting & Waterproofing", lineItem: "Exterior wall painting", unit: "sq.ft", rate: 22, sku: "PNT-121" },
  { sNo: 122, category: "Painting & Waterproofing", lineItem: "Texture/wall finish", unit: "sq.ft", rate: 45, sku: "PNT-122" },
  { sNo: 123, category: "Painting & Waterproofing", lineItem: "Waterproofing — roof", unit: "sq.ft", rate: 65, sku: "PNT-123" },
  { sNo: 124, category: "Painting & Waterproofing", lineItem: "Waterproofing — bathroom/wet area", unit: "sq.ft", rate: 55, sku: "PNT-124" },
  { sNo: 125, category: "Painting & Waterproofing", lineItem: "Primer coat", unit: "sq.ft", rate: 8, sku: "PNT-125" },
  { sNo: 126, category: "Painting & Waterproofing", lineItem: "Putty/plaster of paris", unit: "sq.ft", rate: 12, sku: "PNT-126" },
  { sNo: 127, category: "Office Furniture", lineItem: "Workstation desk", unit: "nos", rate: 12000, sku: "FUR-127" },
  { sNo: 128, category: "Office Furniture", lineItem: "Ergonomic chair", unit: "nos", rate: 8500, sku: "FUR-128" },
  { sNo: 129, category: "Office Furniture", lineItem: "Storage cabinet/filing unit", unit: "nos", rate: 9500, sku: "FUR-129" },
  { sNo: 130, category: "Office Furniture", lineItem: "Conference table", unit: "nos", rate: 35000, sku: "FUR-130" },
  { sNo: 131, category: "Office Furniture", lineItem: "Sofa/lounge seating", unit: "set", rate: 28000, sku: "FUR-131" },
  { sNo: 132, category: "Office Furniture", lineItem: "Reception furniture", unit: "set", rate: 45000, sku: "FUR-132" },
  { sNo: 133, category: "Office Furniture", lineItem: "Cubicle partitions", unit: "nos", rate: 6500, sku: "FUR-133" },
  { sNo: 134, category: "Landscaping & Gardening", lineItem: "Lawn/turfing", unit: "sq.ft", rate: 25, sku: "LND-134" },
  { sNo: 135, category: "Landscaping & Gardening", lineItem: "Plants & shrubs", unit: "nos", rate: 150, sku: "LND-135" },
  { sNo: 136, category: "Landscaping & Gardening", lineItem: "Tree plantation", unit: "nos", rate: 850, sku: "LND-136" },
  { sNo: 137, category: "Landscaping & Gardening", lineItem: "Irrigation — drip/sprinkler", unit: "running ft", rate: 45, sku: "LND-137" },
  { sNo: 138, category: "Landscaping & Gardening", lineItem: "Garden lighting", unit: "nos", rate: 1200, sku: "LND-138" },
  { sNo: 139, category: "Landscaping & Gardening", lineItem: "Pathway/paver blocks", unit: "sq.ft", rate: 85, sku: "LND-139" },
  { sNo: 140, category: "Landscaping & Gardening", lineItem: "Pergola/gazebo", unit: "nos", rate: 45000, sku: "LND-140" },
  { sNo: 141, category: "Landscaping & Gardening", lineItem: "Water fountain", unit: "nos", rate: 25000, sku: "LND-141" },
  { sNo: 142, category: "Swimming Pool Construction", lineItem: "Excavation & civil structure", unit: "sq.ft", rate: 850, sku: "POL-142" },
  { sNo: 143, category: "Swimming Pool Construction", lineItem: "Waterproofing — pool", unit: "sq.ft", rate: 180, sku: "POL-143" },
  { sNo: 144, category: "Swimming Pool Construction", lineItem: "Tiling — pool", unit: "sq.ft", rate: 220, sku: "POL-144" },
  { sNo: 145, category: "Swimming Pool Construction", lineItem: "Filtration system", unit: "nos", rate: 65000, sku: "POL-145" },
  { sNo: 146, category: "Swimming Pool Construction", lineItem: "Pump & motor", unit: "nos", rate: 25000, sku: "POL-146" },
  { sNo: 147, category: "Swimming Pool Construction", lineItem: "Pool lighting", unit: "nos", rate: 3500, sku: "POL-147" },
  { sNo: 148, category: "Swimming Pool Construction", lineItem: "Ladder & handrails", unit: "nos", rate: 8500, sku: "POL-148" },
  { sNo: 149, category: "Swimming Pool Construction", lineItem: "Pool deck", unit: "sq.ft", rate: 180, sku: "POL-149" },
  { sNo: 150, category: "Warehouse Racking Systems", lineItem: "Selective pallet racking", unit: "bay", rate: 8500, sku: "RCK-150" },
  { sNo: 151, category: "Warehouse Racking Systems", lineItem: "Mezzanine flooring", unit: "sq.ft", rate: 450, sku: "RCK-151" },
  { sNo: 152, category: "Warehouse Racking Systems", lineItem: "Shelving units", unit: "nos", rate: 4500, sku: "RCK-152" },
  { sNo: 153, category: "Warehouse Racking Systems", lineItem: "Cantilever racking", unit: "bay", rate: 12000, sku: "RCK-153" },
  { sNo: 154, category: "Warehouse Racking Systems", lineItem: "Safety barriers/guards", unit: "running ft", rate: 850, sku: "RCK-154" },
  { sNo: 155, category: "Warehouse Racking Systems", lineItem: "Ladder/access platform", unit: "nos", rate: 15000, sku: "RCK-155" },
  { sNo: 156, category: "Warehouse Racking Systems", lineItem: "Labeling & signage", unit: "lump sum", rate: 8000, sku: "RCK-156" },
  { sNo: 157, category: "Signage & Branding", lineItem: "Acrylic LED signboard", unit: "sq.ft", rate: 450, sku: "SGN-157" },
  { sNo: 158, category: "Signage & Branding", lineItem: "Glow sign / neon sign", unit: "sq.ft", rate: 650, sku: "SGN-158" },
  { sNo: 159, category: "Signage & Branding", lineItem: "Vinyl branding/wraps", unit: "sq.ft", rate: 85, sku: "SGN-159" },
  { sNo: 160, category: "Signage & Branding", lineItem: "Metal letter signage", unit: "nos", rate: 1200, sku: "SGN-160" },
  { sNo: 161, category: "Signage & Branding", lineItem: "Directional/wayfinding signs", unit: "nos", rate: 850, sku: "SGN-161" },
  { sNo: 162, category: "Signage & Branding", lineItem: "Wall graphics", unit: "sq.ft", rate: 120, sku: "SGN-162" },
  { sNo: 163, category: "Signage & Branding", lineItem: "Standee/banner stand", unit: "nos", rate: 2500, sku: "SGN-163" },
  { sNo: 164, category: "Event / Exhibition Stall Setup", lineItem: "Stall structure/octanorm", unit: "sq.ft", rate: 350, sku: "EVT-164" },
  { sNo: 165, category: "Event / Exhibition Stall Setup", lineItem: "Flooring — carpet/vinyl", unit: "sq.ft", rate: 65, sku: "EVT-165" },
  { sNo: 166, category: "Event / Exhibition Stall Setup", lineItem: "Backdrop/branding panel", unit: "sq.ft", rate: 280, sku: "EVT-166" },
  { sNo: 167, category: "Event / Exhibition Stall Setup", lineItem: "Lighting — spot/track", unit: "nos", rate: 1200, sku: "EVT-167" },
  { sNo: 168, category: "Event / Exhibition Stall Setup", lineItem: "Furniture — table/chairs", unit: "set", rate: 3500, sku: "EVT-168" },
  { sNo: 169, category: "Event / Exhibition Stall Setup", lineItem: "Reception counter", unit: "nos", rate: 8500, sku: "EVT-169" },
  { sNo: 170, category: "Event / Exhibition Stall Setup", lineItem: "Product display racks", unit: "nos", rate: 6500, sku: "EVT-170" },
  { sNo: 171, category: "Event / Exhibition Stall Setup", lineItem: "Power points & wiring", unit: "lump sum", rate: 8000, sku: "EVT-171" },
  { sNo: 172, category: "Borewell & Water Treatment", lineItem: "Borewell drilling", unit: "running ft", rate: 120, sku: "BOR-172" },
  { sNo: 173, category: "Borewell & Water Treatment", lineItem: "Submersible pump & motor", unit: "nos", rate: 22000, sku: "BOR-173" },
  { sNo: 174, category: "Borewell & Water Treatment", lineItem: "Water storage tank", unit: "nos", rate: 18000, sku: "BOR-174" },
  { sNo: 175, category: "Borewell & Water Treatment", lineItem: "RO/water purification plant", unit: "nos", rate: 45000, sku: "BOR-175" },
  { sNo: 176, category: "Borewell & Water Treatment", lineItem: "Softener unit", unit: "nos", rate: 28000, sku: "BOR-176" },
  { sNo: 177, category: "Borewell & Water Treatment", lineItem: "Piping & distribution", unit: "running ft", rate: 65, sku: "BOR-177" },
  { sNo: 178, category: "Borewell & Water Treatment", lineItem: "Water testing", unit: "lump sum", rate: 3500, sku: "BOR-178" },
  { sNo: 179, category: "Elevator / Lift Installation", lineItem: "Lift cabin unit", unit: "nos", rate: 450000, sku: "LFT-179" },
  { sNo: 180, category: "Elevator / Lift Installation", lineItem: "Guide rails", unit: "running ft", rate: 2500, sku: "LFT-180" },
  { sNo: 181, category: "Elevator / Lift Installation", lineItem: "Motor & drive system", unit: "nos", rate: 180000, sku: "LFT-181" },
  { sNo: 182, category: "Elevator / Lift Installation", lineItem: "Control panel", unit: "nos", rate: 85000, sku: "LFT-182" },
  { sNo: 183, category: "Elevator / Lift Installation", lineItem: "Landing doors", unit: "nos", rate: 35000, sku: "LFT-183" },
  { sNo: 184, category: "Elevator / Lift Installation", lineItem: "Safety sensors/interlocks", unit: "set", rate: 25000, sku: "LFT-184" },
  { sNo: 185, category: "Elevator / Lift Installation", lineItem: "Installation & certification", unit: "lump sum", rate: 65000, sku: "LFT-185" },
  { sNo: 186, category: "Home Automation", lineItem: "Smart switches/panel", unit: "nos", rate: 3500, sku: "AUT-186" },
  { sNo: 187, category: "Home Automation", lineItem: "Smart lighting control", unit: "nos", rate: 4500, sku: "AUT-187" },
  { sNo: 188, category: "Home Automation", lineItem: "Motorized curtains/blinds", unit: "nos", rate: 12000, sku: "AUT-188" },
  { sNo: 189, category: "Home Automation", lineItem: "Smart lock/door access", unit: "nos", rate: 8500, sku: "AUT-189" },
  { sNo: 190, category: "Home Automation", lineItem: "Central hub/controller", unit: "nos", rate: 15000, sku: "AUT-190" },
  { sNo: 191, category: "Home Automation", lineItem: "Voice assistant integration", unit: "lump sum", rate: 8000, sku: "AUT-191" },
  { sNo: 192, category: "Home Automation", lineItem: "App/network setup", unit: "lump sum", rate: 6000, sku: "AUT-192" },
  { sNo: 193, category: "Prefab Structures / Steel Sheds", lineItem: "Steel structure/framing", unit: "sq.ft", rate: 450, sku: "PRF-193" },
  { sNo: 194, category: "Prefab Structures / Steel Sheds", lineItem: "Roofing sheets", unit: "sq.ft", rate: 180, sku: "PRF-194" },
  { sNo: 195, category: "Prefab Structures / Steel Sheds", lineItem: "Wall cladding", unit: "sq.ft", rate: 220, sku: "PRF-195" },
  { sNo: 196, category: "Prefab Structures / Steel Sheds", lineItem: "Foundation work", unit: "lump sum", rate: 85000, sku: "PRF-196" },
  { sNo: 197, category: "Prefab Structures / Steel Sheds", lineItem: "Ventilators/skylights", unit: "nos", rate: 4500, sku: "PRF-197" },
  { sNo: 198, category: "Prefab Structures / Steel Sheds", lineItem: "Rolling shutters", unit: "nos", rate: 18000, sku: "PRF-198" },
  { sNo: 199, category: "Prefab Structures / Steel Sheds", lineItem: "Insulation lining", unit: "sq.ft", rate: 120, sku: "PRF-199" },
  { sNo: 200, category: "Commercial Kitchen Equipment", lineItem: "Commercial gas range", unit: "nos", rate: 45000, sku: "CKT-200" },
  { sNo: 201, category: "Commercial Kitchen Equipment", lineItem: "Deep fryer", unit: "nos", rate: 28000, sku: "CKT-201" },
  { sNo: 202, category: "Commercial Kitchen Equipment", lineItem: "Refrigeration — chiller/freezer", unit: "nos", rate: 85000, sku: "CKT-202" },
  { sNo: 203, category: "Commercial Kitchen Equipment", lineItem: "Exhaust hood & ducting", unit: "running ft", rate: 1200, sku: "CKT-203" },
  { sNo: 204, category: "Commercial Kitchen Equipment", lineItem: "Prep tables — stainless steel", unit: "nos", rate: 15000, sku: "CKT-204" },
  { sNo: 205, category: "Commercial Kitchen Equipment", lineItem: "Dishwashing unit", unit: "nos", rate: 65000, sku: "CKT-205" },
  { sNo: 206, category: "Commercial Kitchen Equipment", lineItem: "Storage racks", unit: "nos", rate: 8500, sku: "CKT-206" },
  { sNo: 207, category: "Commercial Kitchen Equipment", lineItem: "Fire suppression system", unit: "lump sum", rate: 45000, sku: "CKT-207" },
  { sNo: 208, category: "Gym / Fitness Equipment Setup", lineItem: "Treadmill", unit: "nos", rate: 85000, sku: "GYM-208" },
  { sNo: 209, category: "Gym / Fitness Equipment Setup", lineItem: "Multi-station gym unit", unit: "nos", rate: 180000, sku: "GYM-209" },
  { sNo: 210, category: "Gym / Fitness Equipment Setup", lineItem: "Free weights & rack", unit: "set", rate: 45000, sku: "GYM-210" },
  { sNo: 211, category: "Gym / Fitness Equipment Setup", lineItem: "Rubber flooring", unit: "sq.ft", rate: 180, sku: "GYM-211" },
  { sNo: 212, category: "Gym / Fitness Equipment Setup", lineItem: "Mirrors — wall", unit: "sq.ft", rate: 250, sku: "GYM-212" },
  { sNo: 213, category: "Gym / Fitness Equipment Setup", lineItem: "Cardio equipment", unit: "nos", rate: 65000, sku: "GYM-213" },
  { sNo: 214, category: "Gym / Fitness Equipment Setup", lineItem: "Locker units", unit: "nos", rate: 12000, sku: "GYM-214" },
  { sNo: 215, category: "Gym / Fitness Equipment Setup", lineItem: "Ventilation/AC provision", unit: "lump sum", rate: 35000, sku: "GYM-215" }
];
